title = "celeste.works"
baseUrl = "https://celeste.works"
disableKinds = ["taxonomy", "taxonomyTerm"]
copyright = "Celeste Horgan"

enableGitInfo = true

[markup.highlight]
style = "paraiso-dark"

[params]
description = "Celeste is an open source advoate and leader. She has worked in open source software since 2025."
font_awesome_version = "5.12.0"
repositoryUrl = "https://github.com/celestehorgan/portfolio"
contentDir = "/content/"

# Metadata mostly used in document's head
# 
keywords = ""
images = [""]


[params.logos]
# navbar = "cncf-color.png"

[[params.social]]
name = "Bluesky"
color = "#9D9D9D"
url = "https://bsky.app/profile/celestehorgan.bsky.social"
icon = "fab fa-bluesky"

[[params.social]]
name = "GitHub"
color = "#9D9D9D"
url = "https://github.com/celestehorgan/"
icon = "fab fa-github"

[[params.social]]
name = "LinkedIn"
color = "#9D9D9D"
url = "https://www.linkedin.com/in/celeste-horgan-b65b5a1a/"
icon = "fab fa-linkedin"

[[params.fonts]]
name = "Fira Sans"
sizes = [300, 400, 600, 700]
type = "sans_serif"

[[params.fonts]]
name = "Fira Mono"
sizes = [300, 400, 600, 700]
type = "monospace"

[[params.fonts]]
name = "Fire Sans"
sizes = [100, 200, 300, 400, 500, 600, 700]
type = "heading_font"

# [[menu.main]]
# name = "Home"
# url = "/"
# weight = 1



[twitter]
  card = "Celeste Horgan"
  site = "{{ .Permalink }}"
  title = "{{ .Title }}"
  description = "{{ if .IsHome }}{{ .Site.Params.description }}{{ else }}{{ .Summary | plainify }}{{ end }}"
  image = "/img/celeste-2021.png"